export const SUPPORTED_VET_CITY_LABELS: Record<string, string> = {
  "new-york-ny": "New York, NY",
  "los-angeles-ca": "Los Angeles, CA",
  "chicago-il": "Chicago, IL",
  "houston-tx": "Houston, TX",
  "philadelphia-pa": "Philadelphia, PA",
  "san-antonio-tx": "San Antonio, TX",
  "san-diego-ca": "San Diego, CA",
  "san-jose-ca": "San Jose, CA",
  "jacksonville-fl": "Jacksonville, FL",
  "fort-worth-tx": "Fort Worth, TX",
  "columbus-oh": "Columbus, OH",
  "charlotte-nc": "Charlotte, NC",
  "indianapolis-in": "Indianapolis, IN",
  "san-francisco-ca": "San Francisco, CA",
  "seattle-wa": "Seattle, WA",
  "denver-co": "Denver, CO",
  "washington-dc": "Washington, DC",
  "boston-ma": "Boston, MA",
  "el-paso-tx": "El Paso, TX",
  "nashville-tn": "Nashville, TN",
  "detroit-mi": "Detroit, MI",
  "oklahoma-city-ok": "Oklahoma City, OK",
  "portland-or": "Portland, OR",
  "las-vegas-nv": "Las Vegas, NV",
  "memphis-tn": "Memphis, TN",
  "louisville-ky": "Louisville, KY",
  "baltimore-md": "Baltimore, MD",
  "milwaukee-wi": "Milwaukee, WI",
  "albuquerque-nm": "Albuquerque, NM",
  "tucson-az": "Tucson, AZ",
  "fresno-ca": "Fresno, CA",
  "sacramento-ca": "Sacramento, CA",
  "mesa-az": "Mesa, AZ",
  "atlanta-ga": "Atlanta, GA",
  "kansas-city-mo": "Kansas City, MO",
  "colorado-springs-co": "Colorado Springs, CO",
  "omaha-ne": "Omaha, NE",
  "raleigh-nc": "Raleigh, NC",
  "dallas-tx": "Dallas, TX",
  "austin-tx": "Austin, TX",
  "miami-fl": "Miami, FL",
  "phoenix-az": "Phoenix, AZ",
  "virginia-beach-va": "Virginia Beach, VA",
  "long-beach-ca": "Long Beach, CA",
  "oakland-ca": "Oakland, CA",
  "minneapolis-mn": "Minneapolis, MN",
  "tulsa-ok": "Tulsa, OK",
  "bakersfield-ca": "Bakersfield, CA",
  "wichita-ks": "Wichita, KS",
  "arlington-tx": "Arlington, TX",
};

export function getVetCityLabel(slug: string): string | undefined {
  return SUPPORTED_VET_CITY_LABELS[slug.toLowerCase().trim()];
}
